### ISSUE TITLE
DrawLine does not draw diagonal lines

### ISSUE THREAD

**Issue by berwil-1** [sumo-digital-academy/playbuffer#1]
The function DrawLine refuses to draw diagonal lines, this for example does not draw anything when it should.
It seems to occur for every diagonal direction (45 degrees) and it's still doable on the latest version (1.1.21.10.11).

`Play::DrawLine(Point2f(100, 100), Point2f(200, 200), Play::cWhite);`

**Comment by sumo-academy-admin** [comment]
Should be fixed in latest version
