### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by rawnsley** [sumo-digital-academy/playbuffer#4]
[The source mentions PlayFontTool](https://github.com/sumo-digital-academy/playbuffer/blob/HelloWorld/Play.h#L1232), but I can't find it anywhere in the repository and there are no search engine hits.

How do we generate custom font sprites?

**Comment by sumo-academy-admin** [comment]
Available in version 2. check out the xtra_PlayBufferCpps branch

https://github.com/sumo-digital-academy/playbuffer/tree/xtra_PlayBufferCpps
